version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - .:/app
#    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
