llm_chat:
  history_repo:
    backend: "disk"
    path: data/chat_history
  chat_service:
    models:
      - backend: "gemini"
        temperature: 1
        api_key: "YOUR_GOOGLE_API_KEY"
      - backend: "gpt-4o"
        temperature: 1
        api_key: "YOUR_OPENAPI_API_KEY"
